- .gitignore
- src/CurvilinearGridFromPolygon.cpp
- src/CurvilinearGridFromSplines.cpp
- src/CurvilinearGridFromSplines.hpp
- src/CurvilinearGridFromSplinesTransfinite.hpp
- src/FlipEdges.cpp
- src/LandBoundaries.cpp
- src/Mesh.cpp
- src/Mesh.hpp
- src/MeshRefinement.cpp
- src/MeshRefinement.hpp
- src/OrthogonalizationAndSmoothing.hpp
- src/Polygons.cpp
- src/Polygons.hpp
- src/SpatialTrees.hpp
According to Wiktionary: "The plural of index is indexes or indices"
> Rename "indexses" to "indices"

- src/tests/PolygonTest.cpp
reactivated unit test, mesh boundary into a polygon
> GRIDEDIT-176: resume unit test

- CMakeLists.txt
- include/MeshKernel/MeshKernel.hpp
- src/MeshKernel.cpp
Also update version number since this is a breaking change
> GRIDEDIT-259: Fix code smells at API level

- include/MeshKernel/CurvilinearGrid.hpp
- include/MeshKernel/CurvilinearGridDeRefinement.hpp
- include/MeshKernelApi/MeshKernel.hpp
- src/MeshKernel/CurvilinearGrid.cpp
- src/MeshKernel/CurvilinearGridCreateUniform.cpp
- src/MeshKernel/CurvilinearGridDeRefinement.cpp
- src/MeshKernel/CurvilinearGridFromPolygon.cpp
- src/MeshKernel/CurvilinearGridFromSplines.cpp
- src/MeshKernel/CurvilinearGridFromSplinesTransfinite.cpp
- src/MeshKernel/CurvilinearGridRefinement.cpp
- src/MeshKernelApi/MeshKernel.cpp
- tests/api/ApiTest.cpp
- tests/unit/CurvilinearGridDeRefinementTest.cpp
- tests/unit/CurvilinearGridRefinementTest.cpp
> GRIDEDIT-333: add curvilinear grid derefinement

- include/MeshKernel/CurvilinearGrid/CurvilinearGrid.hpp
- include/MeshKernel/Mesh.hpp
- include/MeshKernel/RTree.hpp
- include/MeshKernelApi/CurvilinearGrid.hpp
- include/MeshKernelApi/MeshKernel.hpp
- include/MeshKernelApi/Utils.hpp
- src/MeshKernel/AveragingInterpolation.cpp
- src/MeshKernel/Contacts.cpp
- src/MeshKernel/CurvilinearGrid/CurvilinearGrid.cpp
- src/MeshKernel/Mesh.cpp
- src/MeshKernel/RTree.cpp
- src/MeshKernel/TriangulationInterpolation.cpp
- src/MeshKernelApi/MeshKernel.cpp
- tests/api/ApiTest.cpp
- tests/unit/CurvilinearUniformTests.cpp
- tests/utils/include/TestUtils/MakeCurvilinearGrids.hpp
- tests/utils/include/TestUtils/MakeMeshes.hpp
- tests/utils/include/TestUtils/SampleFileReader.hpp
- tests/utils/src/MakeCurvilinearGrids.cpp
- tests/utils/src/MakeMeshes.cpp
- tests/utils/src/SampleFileReader.cpp
Rename RTree::NearestNeighbors to RTree::NearestNeighbor
Add ComputeEdgesAndNodes method in MakeMeshes, for computing 1d/2d edges and nodes from legacy net files
> Correct contacts generation

- include/MeshKernel/Mesh.hpp
- include/MeshKernel/Mesh2D.hpp
- src/MeshKernel/FlipEdges.cpp
- src/MeshKernel/Mesh.cpp
- src/MeshKernel/Mesh2D.cpp
- src/MeshKernel/OrthogonalizationAndSmoothing.cpp
These performance improvements give about 30% speedup
> Some performance improvements

- include/MeshKernel/Entities.hpp
- include/MeshKernel/LandBoundaries.hpp
- include/MeshKernel/Operations.hpp
- include/MeshKernel/Polygons.hpp
- include/MeshKernelApi/Utils.hpp
- src/MeshKernel/CurvilinearGrid/CurvilinearGridCreateUniform.cpp
- src/MeshKernel/CurvilinearGrid/CurvilinearGridFromPolygon.cpp
- src/MeshKernel/CurvilinearGrid/CurvilinearGridFromSplines.cpp
- src/MeshKernel/LandBoundaries.cpp
- src/MeshKernel/Operations.cpp
- src/MeshKernel/Polygons.cpp
- src/MeshKernel/Splines.cpp
- src/MeshKernelApi/MeshKernel.cpp
- tests/unit/Mesh2DTest.cpp
- tests/unit/MeshTests.cpp
Rename m_indices to m_outer_polygons_indices
Use std::pair<size_t, size_t> for indicating the start end end indices of a polygon, instead of std::vector<size_t>
Introduce m_inner_polygons_indices, a map with the index of the current outer polygon and value all the indices of the corresponding inner polygons
> deleting mesh with holes

- tests/benchmark/scripts/html_reporter.py
- tests/benchmark/scripts/json_reader.py
- tests/benchmark/scripts/main.py
- tests/benchmark/scripts/plotter.py
> Added benchmark html reporter

- cmake/compiler_config.cmake
> Bump c++ std from 17 to 20

- libs/MeshKernelApi/CMakeLists.txt
- libs/MeshKernelApi/src/MeshKernel.cpp
> Declare meshKernelState as an unordered_map

- README.md
- cmake/options.cmake
> Improved configuration and build instructions 

- scripts/benchmark_post_processing/requirements.txt
> Added requirements for benchmark post-proc Python scripts

- libs/MeshKernel/benchmark/CMakeLists.txt
> Removed copying of benchmark Python scripts to build dir

- libs/MeshKernelApi/include/MeshKernelApi/MeshKernel.hpp
- libs/MeshKernelApi/include/MeshKernelApi/Utils.hpp
- libs/MeshKernelApi/src/MeshKernel.cpp
- libs/MeshKernelApi/tests/src/ApiTest.cpp
Start renaming api unit test names
> Introduce separate api for making uniform grids on extension

- libs/MeshKernel/CMakeLists.txt
- libs/MeshKernel/include/MeshKernel/BoundingBox.hpp
- libs/MeshKernel/include/MeshKernel/CurvilinearGrid/CurvilinearGridCreateUniform.hpp
- libs/MeshKernel/include/MeshKernel/Entities.hpp
- libs/MeshKernel/include/MeshKernel/Polygons.hpp
- libs/MeshKernel/include/MeshKernel/Vector.hpp
- libs/MeshKernel/src/CurvilinearGrid/CurvilinearGridCreateUniform.cpp
- libs/MeshKernel/src/Mesh.cpp
- libs/MeshKernel/src/Polygons.cpp
- libs/MeshKernel/tests/src/CurvilinearUniformTests.cpp
- libs/MeshKernelApi/tests/src/ApiTest.cpp
related to https://github.com/Deltares/MeshKernelPy/issues/76
> allow generation of curvi grid in polygon for cartisian and spherical coordiantes

- libs/MeshKernel/include/MeshKernel/Mesh.hpp
- libs/MeshKernel/include/MeshKernel/Mesh2D.hpp
- libs/MeshKernel/src/Mesh.cpp
- libs/MeshKernel/src/Mesh2D.cpp
- libs/MeshKernel/src/Polygon.cpp
- libs/MeshKernel/tests/src/MeshRefinementTests.cpp
> GRIDEDIT-695 Removed possibility of computing quads first

- libs/MeshKernel/include/MeshKernel/ConnectMeshes.hpp
- libs/MeshKernel/src/ConnectMeshes.cpp
- libs/MeshKernel/tests/src/Mesh2DConnectDDTest.cpp
- libs/MeshKernelApi/include/MeshKernelApi/MeshKernel.hpp
- libs/MeshKernelApi/src/MeshKernel.cpp
> GRIDEDIT-712 Fixed bug when connecting DD meshes

- libs/MeshKernel/include/MeshKernel/AveragingInterpolation.hpp
- libs/MeshKernel/include/MeshKernel/AveragingStrategies/AveragingStrategy.hpp
- libs/MeshKernel/include/MeshKernel/AveragingStrategies/AveragingStrategyFactory.hpp
- libs/MeshKernel/include/MeshKernel/AveragingStrategies/ClosestAveragingStrategy.hpp
- libs/MeshKernel/include/MeshKernel/AveragingStrategies/InverseWeightedAveragingStrategy.hpp
- libs/MeshKernel/include/MeshKernel/AveragingStrategies/MaxAveragingStrategy.hpp
- libs/MeshKernel/include/MeshKernel/AveragingStrategies/MinAbsAveragingStrategy.hpp
- libs/MeshKernel/include/MeshKernel/AveragingStrategies/MinAveragingStrategy.hpp
- libs/MeshKernel/include/MeshKernel/AveragingStrategies/SimpleAveragingStrategy.hpp
- libs/MeshKernel/src/AveragingInterpolation.cpp
- libs/MeshKernel/src/AveragingStrategies/AveragingStrategyFactory.cpp
- libs/MeshKernel/src/AveragingStrategies/ClosestAveragingStrategy.cpp
- libs/MeshKernel/src/AveragingStrategies/InverseWeightedAveragingStrategy.cpp
- libs/MeshKernel/src/AveragingStrategies/MaxAveragingStrategy.cpp
- libs/MeshKernel/src/AveragingStrategies/MinAbsAveragingStrategy.cpp
- libs/MeshKernel/src/AveragingStrategies/MinAveragingStrategy.cpp
- libs/MeshKernel/src/AveragingStrategies/SimpleAveragingStrategy.cpp
- libs/MeshKernel/tests/src/AveragingStrategyTests.cpp
This branch contains only the refactoring of the averaging strategies
> GRIDEDIT-785 Refactoring of the averaging strategy

- libs/MeshKernelApi/src/MeshKernel.cpp
- libs/MeshKernelApi/tests/src/CurvilinearGridTests.cpp
add swapping in mkernel_curvilinear_set
> add MakeRectangular_ConvertToMesh2D test

- CMakeLists.txt
> Release v4.2.0

- CMakeLists.txt
> Release v4.3.0

- CMakeLists.txt
> Release v5.0.0

- CMakeLists.txt
> Release v5.0.2

- .github/workflows/build-and-test-feature-master.yml
- .github/workflows/build-and-test-release.yml
remove unsupported macos-12 runner. Substitute macos-12 with macos-13 in build and test configuration
> GRIDEDIT-1343: remove unsupported macos-12. runner

- CMakeLists.txt
> Release v6.0.0

- CMakeLists.txt
> Release v6.0.1

- CMakeLists.txt
> Release v7.0.0

- libs/MeshKernel/benchmark/src/perf_orthogonalization.cpp
Changed parameters to orthogonalisation and smoothing constructor
> GRIDEDIT-1829 Fixed benchmark build
